package com.remotelinkdesk.app

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.widget.TextView
import android.widget.Toast

class MainActivity : AppCompatActivity() {

    // Load the Rust Shared Object library (.so) generated by our `jni_bridge` crate
    companion object {
        init {
            System.loadLibrary("jni_bridge")
        }
    }

    // Declare the native function implemented in `shared/jni_bridge/src/lib.rs`
    private external fun getCoreVersion(): String

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        
        // Simple UI setup (Normally we'd use XML layouts or Jetpack Compose)
        val textView = TextView(this).apply {
            textSize = 20f
            setPadding(32, 32, 32, 32)
        }
        
        setContentView(textView)
        
        try {
            // Call the Rust engine directly!
            val rustVersion = getCoreVersion()
            textView.text = "Success!\n\n$rustVersion"
            
            Toast.makeText(this, "Rust Core Initialized", Toast.LENGTH_SHORT).show()
        } catch (e: Exception) {
            textView.text = "Failed to load Rust JNI bridge: ${e.message}"
        }
    }
}
